### ISSUE TITLE
Pytorch_pretrained_model

### ISSUE THREAD

**Issue by zysNLP** [yao8839836/kg_bert#1]
when I exectute

python run_bert_triple_classifier.py 
--task_name kg
--do_train  
--do_eval 
--do_predict 
--data_dir ./data/WN11 
--bert_model bert-base-uncased 
--max_seq_length 20 
--train_batch_size 32 
--learning_rate 5e-5 
--num_train_epochs 3.0 
--output_dir ./output_WN11/  
--gradient_accumulation_steps 1 
--eval_batch_size 512

it turned out that a pytorch_pretrained_file is downloading.
I found it too slow to download. so I copy:
https://s3.amazonaws.com/models.huggingface.co/bert/bert-base-uncased.tar.gz
to download alone.

**Comment by zysNLP** [comment]
I want to ask where should I put this "bert-base-uncased.tar.gz"? Thank you!

**Comment by yao8839836** [comment]
@zysNLP 

In Linux or Mac OS, the temporary vocab file is under "/Users/myname/.pytorch_pretrained_bert/" and the model file is under "/Users/myname/.pytorch_pretrained_bert/distributed_-1/" (no distributed training).  I didn't try Windows, but it should be under some similar user folders.

**Comment by zysNLP** [comment]
@yao8839836 您好，我没有在linux下找到这个文件路径，/Users/看起来更像是windows下的那个文件夹，linux的文件好像不能以"."开头。。

**Comment by yao8839836** [comment]
@zysNLP 

您好，我是在我的MAC下找的，您可以看下pytorch-pretrained-bert这个库的源码，我是直接安装然后调用的，下载模型的代码应该可以定位到。

**Comment by zysNLP** [comment]
@yao8839836 好的，多谢！
