### ISSUE TITLE
commands not working for prediction 

### ISSUE THREAD

**Issue by ChloeJKim** [yao8839836/kg_bert#18]
Hi 
Thanks for posting your code! love your work and wanted to reproduce the result.

For 3. Link Prediction (UMLS) 
I ran the exact same command as you posted but get this. Can you help me how I can fix this?

python3 run_bert_link_prediction.py
--task_name kg  
--do_train  
--do_eval 
--do_predict 
--data_dir ./data/umls
--bert_model bert-base-uncased
--max_seq_length 15
--train_batch_size 32 
--learning_rate 5e-5 
--num_train_epochs 5.0 
--output_dir ./output_umls/  
--gradient_accumulation_steps 1 
--eval_batch_size 135

![image](https://user-images.githubusercontent.com/52466133/93175835-23fdca00-f6e5-11ea-86d3-8463c2bb6704.png)

Thank you in advance

**Comment by yao8839836** [comment]
@ChloeJKim 

Thank you! The command should be in the same command line.
