### ISSUE TITLE
How to implement pretrained model from the output folder

### ISSUE THREAD

**Issue by moh-yani** [yao8839836/kg_bert#3]
I have run the run_bert_classifier.py. That process outputs a folder name output_FB15K. It contains *.json; *.bin and vocab.txt files. The question is how I can implement those files to check whether a given triple is correct or not? 

For instance, if  I give a triple 453 1347 37, how I can check if that triple is correct or not. Anyone could give an example script to do that?

**Comment by yao8839836** [comment]
@moh-yani

The script should be similar to line 777--828 in run_bert_triple_classifier.py. 

You need to assign your test triple  453 1347 37 to eval_examples in line 777 (which will have only one example),

then preds in line 828 will be the label which indicates if the triple is correct or not.

**Comment by moh-yani** [comment]
@yao8839836

If I assign the triple to eval_example in line 777, does it mean I just need to assign the Ids (such as 453 1347 37) or completely assign the mids in the test.tsv file (for instance: /m/01qscs	/award/award_nominee/award_nominations./award/award_nomination/award	/m/02x8n1n)?
