### ISSUE TITLE
Time complexity of test triple ranking

### ISSUE THREAD

**Issue by xyjigsaw** [yao8839836/kg_bert#31]
Hi there, you mentioned that
> Each correct test triple (h, r, t) is corrupted by replacing either its head or tail entity with every entity $e \in E$.

which means, in my opinion, the time complexity of $N$ test triples ranking is $N \times |E|$.
I wonder whether it is time-consuming?

**Comment by yao8839836** [comment]
@xyjigsaw Yes, it‘s time-consuming in the evaluation phase. The limitation has been addressed in https://arxiv.org/abs/2004.14781

**Comment by xyjigsaw** [comment]
Thank you for your quick response.
