### ISSUE TITLE
请问该文发表到正式期刊或会议了吗？

### ISSUE THREAD

**Issue by ghost** [yao8839836/kg_bert#34]
您好，请问该文发表到正式期刊或会议了吗？
我们想引用本文，但发表于正式期刊或会议的论文，可能会更有说服力。

**Comment by yao8839836** [comment]
@TankAbraham 您好，感谢您对我们工作的兴趣，目前还没有，正处在一个期刊修改阶段。您可以引用arxiv版本，谢谢~

**Comment by ghost** [comment]
> 

感谢回复！
