### ISSUE TITLE
关于FB15K-237数据集文本句子的问题

### ISSUE THREAD

**Issue by Vin1115** [yao8839836/kg_bert#36]
作者您好，我想请问您给出的数据集FB15k-237中的entity2text.txt文件是如何生成的，因为原数据集上entity文件并没有给出实际的文本表示，只有编码表示（如/m/02zyy4），请问是通过什么途径获得的该词实际的表示（/m/02zyy4	Michael Madsen）呢？希望您能给出解答，谢谢！

**Comment by yao8839836** [comment]
@Vin1115 

您好，印象中是从https://github.com/xrb92/DKRL  的FB15K的实体描述获得的，FB15k-237是FB15K的子集。

**Comment by Vin1115** [comment]
十分感谢！
