### ISSUE TITLE
运行配置与时间

### ISSUE THREAD

**Issue by yw3l** [yao8839836/kg_bert#44]
你好！@yao8839836 
        非常有意义的工作！请问方便告诉我您在WN18RR与FB15k-237数据集上的运行时间吗？或者告诉我配置，我复现看下时间。谢谢！这对我帮助很大。

**Comment by yao8839836** [comment]
@yw3l  你好，用V100的话，训练时间一般1-2小时，推理时间会比较久，WN18RR需要1-2天左右，FB15k-237更久。因为link prediction任务对于每个测试三元组，需要把头/尾实体换成所有其他实体经过BERT计算得分。

后续工作有针对这个做出改进，例如：

https://arxiv.org/abs/2004.14781
https://aclanthology.org/2022.acl-long.295/

**Comment by yw3l** [comment]
@yao8839836 谢谢！
需要把头/尾实体换成所有其他实体经过BERT计算得分。 是在做候选-排序-打分吗？

**Comment by yao8839836** [comment]
> @yao8839836 谢谢！ 需要把头/尾实体换成所有其他实体经过BERT计算得分。 是在做候选-排序-打分吗？

@yw3l 是的, link pediction任务就是对所有实体排序。看真正的实体的排名情况。

**Comment by yw3l** [comment]
谢谢！StAR我了解过；SimKGC我仔细看了，事实上，我在其iuuse见过您的回复。这两篇工作也是非常不错。再次感谢您的回复！
