### ISSUE TITLE
Train run_bert_link_prediction.py is still ongoing for 7 days

### ISSUE THREAD

**Issue by moh-yani** [yao8839836/kg_bert#8]
I am trying perform run_bert_link_prediction.py for FB15K data with GPU 8GB and 12 batch_size. After 7 days, it is still ongoing. The iteration process shows:
Testing: 100%
left: ???
Testing: 100%
right: ???
mean rank until now: ???
hit@10 until now: ???

Is it normal? how long to perform that file in your experience?

**Comment by yao8839836** [comment]
@moh-yani 

It's normal, I spent more than 30 days to evaluate link prediction on FB15K-237, and WN18RR cost several days on a V100 GPU. The evaluation needs to replace every head/tail entity in every test triple with all entities in a knowledge graph and obtains the ranks. On ther other hand, BERT is a heavy model which needs a lot of computation.

**Comment by moh-yani** [comment]
Okay, thanks.
